version: 0.2

env:
    variables:
        # S3_BUCKET: "forzapp-build"
        APP_NAME: "timesheet-sonda"
        # BUILD_ENV : "prd"

phases:
    install:
        runtime-versions:
            java: openjdk8
    pre_build:
        commands:
          - echo [PHASE] Entered the pre_build phase...
          - chmod +x ./gradlew
      
    build:
        commands:
          - echo [PHASE] Entered the build phase...
          - ./gradlew build
  
    post_build:
        commands:

artifacts:
  files:
    - 'build/libs/*.jar'
    - 'Procfile'